-- Workout plans generated by AI
create table if not exists public.workout_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  difficulty_level text check (difficulty_level in ('beginner', 'intermediate', 'advanced')) default 'beginner',
  duration_weeks integer default 1,
  is_active boolean default true,
  ai_model text,
  created_at timestamptz default now()
);

alter table public.workout_plans enable row level security;
create policy "workout_plans_select_own" on public.workout_plans for select using (auth.uid() = user_id);
create policy "workout_plans_insert_own" on public.workout_plans for insert with check (auth.uid() = user_id);
create policy "workout_plans_update_own" on public.workout_plans for update using (auth.uid() = user_id);
create policy "workout_plans_delete_own" on public.workout_plans for delete using (auth.uid() = user_id);

-- Daily workouts within a plan
create table if not exists public.daily_workouts (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.workout_plans(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  day_number integer not null check (day_number between 1 and 7),
  day_name text not null,
  workout_type text not null,
  is_rest_day boolean default false,
  estimated_duration_min integer,
  calories_burn_estimate integer,
  completed boolean default false,
  completed_at timestamptz,
  difficulty_rating integer check (difficulty_rating between 1 and 5),
  notes text,
  created_at timestamptz default now()
);

alter table public.daily_workouts enable row level security;
create policy "daily_workouts_select_own" on public.daily_workouts for select using (auth.uid() = user_id);
create policy "daily_workouts_insert_own" on public.daily_workouts for insert with check (auth.uid() = user_id);
create policy "daily_workouts_update_own" on public.daily_workouts for update using (auth.uid() = user_id);
create policy "daily_workouts_delete_own" on public.daily_workouts for delete using (auth.uid() = user_id);

-- Exercises within a daily workout
create table if not exists public.exercises (
  id uuid primary key default gen_random_uuid(),
  daily_workout_id uuid not null references public.daily_workouts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  muscle_group text,
  sets integer,
  reps text,
  weight_suggestion text,
  rest_seconds integer,
  duration_seconds integer,
  order_index integer not null default 0,
  completed boolean default false,
  created_at timestamptz default now()
);

alter table public.exercises enable row level security;
create policy "exercises_select_own" on public.exercises for select using (auth.uid() = user_id);
create policy "exercises_insert_own" on public.exercises for insert with check (auth.uid() = user_id);
create policy "exercises_update_own" on public.exercises for update using (auth.uid() = user_id);
create policy "exercises_delete_own" on public.exercises for delete using (auth.uid() = user_id);
