-- Nutrition plans generated by AI
create table if not exists public.nutrition_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan_id uuid references public.workout_plans(id) on delete set null,
  tdee_estimate integer,
  calorie_target integer,
  protein_g integer,
  carbs_g integer,
  fat_g integer,
  meals_per_day integer default 3,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.nutrition_plans enable row level security;
create policy "nutrition_plans_select_own" on public.nutrition_plans for select using (auth.uid() = user_id);
create policy "nutrition_plans_insert_own" on public.nutrition_plans for insert with check (auth.uid() = user_id);
create policy "nutrition_plans_update_own" on public.nutrition_plans for update using (auth.uid() = user_id);
create policy "nutrition_plans_delete_own" on public.nutrition_plans for delete using (auth.uid() = user_id);

-- Individual meals
create table if not exists public.meals (
  id uuid primary key default gen_random_uuid(),
  nutrition_plan_id uuid not null references public.nutrition_plans(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  day_number integer not null check (day_number between 1 and 7),
  meal_type text not null check (meal_type in ('breakfast', 'lunch', 'dinner', 'snack')),
  meal_name text not null,
  description text,
  calories integer,
  protein_g integer,
  carbs_g integer,
  fat_g integer,
  ingredients text[],
  created_at timestamptz default now()
);

alter table public.meals enable row level security;
create policy "meals_select_own" on public.meals for select using (auth.uid() = user_id);
create policy "meals_insert_own" on public.meals for insert with check (auth.uid() = user_id);
create policy "meals_update_own" on public.meals for update using (auth.uid() = user_id);
create policy "meals_delete_own" on public.meals for delete using (auth.uid() = user_id);

-- Progress tracking (weight, body metrics over time)
create table if not exists public.progress_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  weight_kg numeric,
  body_fat_pct numeric,
  energy_level integer check (energy_level between 1 and 5),
  sleep_hours numeric,
  mood integer check (mood between 1 and 5),
  notes text,
  logged_at date default current_date,
  created_at timestamptz default now()
);

alter table public.progress_logs enable row level security;
create policy "progress_logs_select_own" on public.progress_logs for select using (auth.uid() = user_id);
create policy "progress_logs_insert_own" on public.progress_logs for insert with check (auth.uid() = user_id);
create policy "progress_logs_update_own" on public.progress_logs for update using (auth.uid() = user_id);
create policy "progress_logs_delete_own" on public.progress_logs for delete using (auth.uid() = user_id);
